### ISSUE TITLE
No /dev/gpiochip0 on Artik 530s

### ISSUE THREAD

**Issue by andrewjaykeller** [rust-embedded/gpio-cdev#11]
I want to use this driver to see if it is more performant than sysfs. The one problem I'm running into is there is no `gpiochip0` listed under `/dev`. 

How do I add `gpiochip0` to `/dev` so I can start using this library?

Thanks so much for all your hard work and help! Go rust!

**Comment by fpagliughi** [comment]
The GPIO device is part of the Linux kernel port for the board. It may or may not be implemented for the board, or it may not be configured and compiled into your kernel, or maybe it's not configured for your device tree. Check to see if there's help for that board or a forum where you can post the question.

But if you're just looking to play around to see what it can do, maybe the easiest thing is to do is get a Raspberry Pi or BeagleBone Black/Green/etc. Those have GPIO char device support out-of-the-box.
