### ISSUE TITLE
Won't compile on Raspberry Pi

### ISSUE THREAD

**Issue by drinkdhmo** [rust-embedded/gpio-cdev#13]
Version 0.2.0 has a dependency on `nix` version 0.11.0, which does not compile on the Raspberry Pi. This is fixed in `nix` version 0.14.0. See https://github.com/nix-rust/nix/issues/1057

**Comment by elihunter173** [comment]
Shouldn't this be closed?

**Comment by posborne** [comment]
> Shouldn't this be closed?

Thanks, closing.  Currently on nix 0.14.
