### ISSUE TITLE
Remove error-chain and manually implement an error type.

### ISSUE THREAD

**Issue by chris-ricketts** [rust-embedded/gpio-cdev#25]
As discussed in #24 

This would remove a dependency and give end users of the library more flexibility to handle errors how they wish.

`error-chain` is going to be deprecated in any case. 

The new error type should endeavor to play nicely with [failure](https://docs.rs/failure/0.1.6/failure/trait.Fail.html) without having a direct dependency on it.

**Comment by chris-ricketts** [comment]
Any thoughts on #26?

**Comment by posborne** [comment]
> Any thoughts on #26?

Sorry, got buried.  I'll try to get to it in the next 24 hours.
