### ISSUE TITLE
Replace error-chain with std::error::Error

### ISSUE THREAD

**Issue by bestouff** [rust-embedded/gpio-cdev#36]
Impossible to use `anyhow` with `gpio-cdev`:

```
error[E0277]: `(dyn std::error::Error + std::marker::Send + 'static)` cannot be shared between threads safely
 --> src/main.rs:9:52
  |
9 |     let mut chip = gpio_cdev::Chip::new(RELAY_CHIP)?;
  |                                                    ^ `(dyn std::error::Error + std::marker::Send + 'static)` cannot be shared between threads safely
  |
  = help: the trait `std::marker::Sync` is not implemented for `(dyn std::error::Error + std::marker::Send + 'static)`
  = note: required because of the requirements on the impl of `std::marker::Sync` for `std::ptr::Unique<(dyn std::error::Error + std::marker::Send + 'static)>`
  = note: required because it appears within the type `std::boxed::Box<(dyn std::error::Error + std::marker::Send + 'static)>`
  = note: required because it appears within the type `std::option::Option<std::boxed::Box<(dyn std::error::Error + std::marker::Send + 'static)>>`
  = note: required because it appears within the type `error_chain::State`
  = note: required because it appears within the type `gpio_cdev::errors::Error`
  = note: required because of the requirements on the impl of `std::convert::From<gpio_cdev::errors::Error>` for `anyhow::Error`
  = note: required by `std::convert::From::from`
```

**Comment by nastevens** [comment]
This is a side-effect of using error-chain, which isn't really needed with the stabilization of good `std::error::Error` support. Moving off of error-chain seems reasonable to me. I'm going to retitle this to reflect the move from error-chain to `std::error::Error`

**Comment by bestouff** [comment]
You should probably consider using [`thiserror`](https://docs.rs/thiserror), which is a helper for writing `std::error:Error`-derived errors and doesn't add anything to the exported interface.

**Comment by fpagliughi** [comment]
I've been using `thiserror` lately and am pretty happy with it.

I can convert this project to use `thiserror` if you want. It's easy enough.

**Comment by fpagliughi** [comment]
OK. Now I'm confused. `src/errors.rs` seems to have a hand-written std::errors implementation with the examples using `anyhow` from last Oct. 

Has this just not been published to crates.io?

**Comment by nastevens** [comment]
> Has this just not been published to crates.io?

Looks like that is the case - `Cargo.toml` has even been updated to 0.3 but 0.2 is what's on crates.io. I'll pester @posborne and see if we can get this released.

**Comment by posborne** [comment]
0.3.0 is now published: https://crates.io/crates/gpio-cdev.  Sorry for the delay and thanks for the ping @nastevens

**Comment by nastevens** [comment]
Thanks Paul - closing this as anyhow is now properly supported 👍

**Comment by bestouff** [comment]
Thanks everyone !

**Comment by fpagliughi** [comment]
Well that was easy.
