### ISSUE TITLE
gpio-cdev = { version = "0.3", features = ["async-tokio"] } fails

### ISSUE THREAD

**Issue by emilhoeiriis** [rust-embedded/gpio-cdev#38]
Create a new project `foo` with `gpio-cdev` as a dependency with the _async-tokio_ feature.
```
[dependencies]
gpio-cdev = { version = "0.3", features = ["async-tokio"] }
```
This gives us an error
```
... the package `foo` depends on `gpio-cdev`, with features: `async-tokio` but `gpio-cdev` does not have these features.
```

**Comment by posborne** [comment]
@ryankurte Thanks for the bump; that reminds me that I have a branch doing some polish sitting on my drive ready to be finished up to prep the next release.  I'll get that up.

**Comment by posborne** [comment]
https://github.com/rust-embedded/gpio-cdev/pull/40

**Comment by posborne** [comment]
0.4.0 is now published https://crates.io/crates/gpio-cdev
