### ISSUE TITLE
Switch CI to GitHub Actions

### ISSUE THREAD

**Issue by eldruin** [rust-embedded/gpio-cdev#48]
Travis is shutting down and running a build to completion is already quite impossible.

**Comment by ryankurte** [comment]
should -pretty much- be able to grab the config from [linux-embedded-hal](https://github.com/rust-embedded/linux-embedded-hal/tree/master/.github/workflows) i suspect

**Comment by eldruin** [comment]
Kind of, but the CI here uses [cross](https://github.com/rust-embedded/gpio-cdev/blob/master/ci/install.sh) and supports some deploy steps.
